### ISSUE TITLE
recurring errors in console

### ISSUE THREAD

**Issue by ak4t0sh** [damianxd/atto_studietube#4]
It seems that for each resource an ajax query like the following is sent every 5s but is failling. 
https://www.skoletube.dk/notiserv/?userdata=skoletube%3Auid462108&time=1556537183&key=xxxxxxxxxxxxxxxxxxxxxxxxxxx&dev=1&first=true&server=skoletube&winid=Ud4F2JAlJ0Bp_sub145&ts=0&callback=jQuery32103752609344355332_1556537184617&_=1556537184618

I got an Error 502 with the following response :  
[response.html.txt](https://github.com/damianxd/atto_studietube/files/3127282/response.html.txt)

Which cause the following error
```
SyntaxError: expected expression, got '<'[Learn More] 0:1
	p https://www.skoletube.dk/sk-temp/statics/19.01/laerit.min.js:1:516
	globalEval https://www.skoletube.dk/sk-temp/statics/19.01/laerit.min.js:1:2581
	text script https://www.skoletube.dk/sk-temp/statics/19.01/laerit.min.js:1:81125
	Qb https://www.skoletube.dk/sk-temp/statics/19.01/laerit.min.js:1:74283
	A https://www.skoletube.dk/sk-temp/statics/19.01/laerit.min.js:1:77810
	c/< https://www.skoletube.dk/sk-temp/statics/19.01/laerit.min.js:1:80414
```

**Comment by damianxd** [comment]
fixed
