### ISSUE TITLE
multiple editor handling

### ISSUE THREAD

**Issue by ak4t0sh** [damianxd/atto_studietube#5]
When a page have multiple atto editors (question editions for example) and you want to add a resource in one of them it will automatically be added into all atto fields.

For example in the following screenshot I added a resource in "question text" field only but it automatically appear in feedbacks.
Reproduced on Moodle 3.5 and 3.6 in true/false question creation

![image](https://user-images.githubusercontent.com/2222386/56908140-073c0480-6aa6-11e9-9704-b656b135a28f.png)

(The blue header in the center is due to firefox screenshot you can ignore it ;))

**Comment by damianxd** [comment]
fixed
